name: MM
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.8.10
  - pytorch=2.1
  #- torchvision=0.12.0
  #- cudatoolkit=11.3
  - pandas=1.4.1
  - nb_conda
  - numpy=1.24.3
  - openblas
  - ipywidgets
  - matplotlib
  - tqdm=4.59.0
  - docopt=0.6.2
  - jupyter
  - notebook
  - xgboost
  - seaborn
  - shap
  - umap-learn
  - pip=21.1.2
  - plotly
  - python-kaleido
  # https://github.com/neuropsychology/NeuroKit?tab=readme-ov-file
  - neurokit2 # ECG computation kit
  - neurodsp # wavelet computation kit
  - pywavelets # variety of wavelet computation kit
  - pip:
    - kymatio
    - scipy
    - sklearn
    - cebra
    - chardet
    - mat73
    - sentencepiece
    - mne
    - jupyter_contrib_nbextensions
    - biosppy
    - sacrebleu
    - nltk
    - timeout_decorator
