name: MM
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - openblas
  - ipywidgets
  - python=3.8.10
  - pandas=1.4.1
  - numpy=1.24.3
  - scipy
  - scikit-learn
  - matplotlib
  - tqdm=4.59.0
  - docopt=0.6.2
  - notebook
  - xgboost
  - seaborn
  - shap
  - umap-learn
  - pip=21.1.2
  - plotly
  - python-kaleido
  - pip:
      - mat73
      - sentencepiece
      - mne
      - jupyter_contrib_nbextensions
      - biosppy
      - sacrebleu
      - nltk
      - timeout_decorator
